### ISSUE TITLE
npm start --> Watch update files in the wrong folder 

### ISSUE THREAD

**Issue by zaras00tra** [StartBootstrap/startbootstrap-creative#208]
Hello, I have an issue. 

When I "npm start", then update my index.pug. That create and update in the same folder an "index.html" instead of updateding the one in dist. 

I am on windows 10 and I am using VS code. 

`[SB_WATCH] ### INFO: Rendering src\pug\index.pug to src\pug\index.html
[SB_WATCH] ### INFO: File event: change: src\pug\index.html`

**Comment by Scott-G** [comment]
Replace the  following line in `scripts/render-pug.js`

`const destPath = filePath.replace(/src\/pug\//, 'dist/').replace(/\.pug$/, '.html');`
to
` const destPath = filePath.replace(/src\/pug|src\\pug/, 'dist').replace(/\.pug$/, '.html');`
It won't be the most efficient regex and I dare say someone will have a much better option, but it should do the job for now.

**Comment by davidtmiller** [comment]
I will take a look at this. We work mostly on Mac, so I'll run a test on Windows 10 and see if I can come up with a fix here. Thanks!

**Comment by gavinr** [comment]
I had this same issue, and @Scott-G's solution works for me on Windows 10.

**Comment by davidtmiller** [comment]
I will be updating the scripts to use upath which was the fix we pushed for the same issue that pro product users were experiencing. That change will get bundled into the Bootstrap 4.6 release, and from there will be included with the Bootstrap 5 releases for this (and all other) themes. Thanks for the heads up with this issue!

**Comment by davidtmiller** [comment]
Should be fixed as of e1438ee5b84e440af57a848dc93bde6f2d0448db
