### ISSUE TITLE
 How can I publish my portfolio via github?

### ISSUE THREAD

**Issue by maximilianofni** [StartBootstrap/startbootstrap-creative#224]
# Hello, I need to know how to publish my portfolio? , I already edited all things in startbootstrap-creative, thanks

**Comment by davidtmiller** [comment]
We go over this a bit in a guide covering [how to publish a Start Bootstrap theme on GitHub Pages](https://startbootstrap.com/guides/how-to-create-a-website-with-github-pages). That would be a good starting point.

You can also check out the [GitHub Pages docs](https://docs.github.com/en/github/working-with-github-pages/creating-a-github-pages-site) for some more help!
