### ISSUE TITLE
Issue with running npm start

### ISSUE THREAD

**Issue by cc743** [StartBootstrap/startbootstrap-creative#232]
Hello, 

Something is deadly wrong with running _npm start_, which launches a live preview in the default browser and watches for changes made to files in _dist_.

Every time I launch npm start, it reverts all changes made to the files in _dist_ to what was originally in the source code (_Your favorite source of bootstrap themes_, etc.)

I was working on my portfolio website for two days with this template, and I was using _npm start_ to track my changes with a live preview.  I was continually saving changes, then I exited the live preview by pressing _Ctrl + C_ on my terminal.  I run npm start to return to work and everything was reverted back into what was in the source code.  Somewhere in this process, I lost all my work.

I try again by making some quick changes in the masthead in _index.html_ , and I saw that once I run _npm start_, everything in the masthead changes back (again, _Your favorite source of bootstrap themes_, etc.)

May you have a look at this and see if you run into the same issue that I had?

**Comment by cc743** [comment]
Sorry, I made a writing mistake. When I wrote the following: 
changes to files made in _src_

I meant:
changes to files made in _dist_

**Comment by anthony-langham** [comment]
I have a similar issue, but the original code is restored when deployed to netlify, which is using "npm run build" - not sure how to solve it, if you could advise that would be great - thank you
