### ISSUE TITLE
Accordion is broken

### ISSUE THREAD

**Issue by rockoder** [StartBootstrap/startbootstrap-creative#238]
I am trying to add a FAQ section. However when I use the following bootstrap code:
https://getbootstrap.com/docs/5.0/components/accordion/

the accordion does not render properly. They do not expand, collapse etc:
![image](https://user-images.githubusercontent.com/2136164/126868839-eaf19cc9-45c9-45e8-8cb0-11d0b80cdc8b.png)

Is this a issue or am I missing something?

**Comment by davidtmiller** [comment]
This would not be an issue with the theme. Based on the screenshot it looks like the JS and CSS isn't loading properly.
